# -*- coding: utf-8 -*-
"""creadit_card fraud detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1js5IxIrPl_ODHrvPOSWXmS4RP2dIFC9A
"""

#Importing Labs.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter
import  itertools

#Loading Dataset.
df=pd.read_csv("/content/creditcard.csv")

#Inspecting rows & columns.
df.shape

#Inspecting Data.
df.head()

#Inspecting Amount column.
df['Amount'].describe()

df.dropna(inplace=True)

#Inspecting Null Values.
df.isnull().sum()

#Inspecting fraud vs non fraud data
df['Class'].value_counts()

#Calculting percentage of fraud vs non fraud.
fraud = len(df[df['Class'] == 1])
non_fraud = len(df[df['Class']==0])
percentage=(fraud/(non_fraud+fraud))*100
print("Number of Genuine transactions: ", non_fraud)
print("Number of Fraud transactions: ", fraud)
print("Percentage of Fraud transactions: {:.4f}".format(percentage))

# Plotting a bar plot to get a count of, genuine, class and fraud


import matplotlib.pyplot as plt
labels = ['Genuine','Fraud']
count_classes = df.value_counts(df['Class'], sort = True)
count_classes.plot(kind="bar", rot= 0)
plt.title("Visulialization of labels")
plt.ylabel("Count")
plt.xticks(range(2), labels)
plt.show()

#Droping the Target Column.
df.drop(['Time'],inplace=True,axis = 1)
x = df.drop(['Class'],axis=1)
y = df['Class']

# Splitting the data into train, test(0.3)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=11)

from sklearn.preprocessing import StandardScaler
#Scaling the data on Amount column.
# Re-initialize x_train, x_test, y_train, y_test to ensure 'Amount' column is numerical
# Using the same random_state=11 for reproducibility
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=11)

scaler= StandardScaler()

x_train['Amount']= scaler.fit_transform(x_train[['Amount']])
x_test['Amount']= scaler.transform(x_test[['Amount']])

#Building the DecisionTreeClassifier

from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(max_depth=5,class_weight='balanced',random_state=22)
dt.fit(x_train,y_train)

#Predictions of DecisionTree
dt_pred = dt.predict(x_test)
dt_pred

from sklearn.metrics import accuracy_score
# Validating Accuracy of model.
dt_acc= accuracy_score(y_test,dt_pred)
dt_acc

# Confusin Matrics
from sklearn.metrics import confusion_matrix
dt_cm = confusion_matrix(y_test,dt_pred)


print(f"Confusion Matrix for Decision Tree:\n{dt_cm}")

#Building Random Forest Model.

from sklearn.ensemble import RandomForestClassifier

from sklearn.ensemble import RandomForestClassifier

# Added 'max_depth' and 'min_samples_split' to stop trees from growing endlessly
rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,            # Prevents trees from memorizing unique anomalies
    min_samples_split=5,     # Requires more data points before making a rule
    class_weight="balanced",
    random_state=15,
    n_jobs=-1                # Uses all processor cores to speed up training
)

rf.fit(x_train, y_train)

#Validating  accuracy of a  RandomForest.
rf_pred = rf.predict(x_test)
rf_acc=accuracy_score(y_test,rf_pred)
rf_acc

print("dt_accuracy", dt_acc)
print("rf_accuracy", rf_acc)

from sklearn.metrics import confusion_matrix
rf_cm=confusion_matrix(y_test, rf_pred)


print(f"Confusion Matrix for Random Forest:\n{rf_cm}")

from sklearn.metrics import classification_report

# 1. Print metrics for Decision Tree
print("================ DECISION TREE METRICS ================")
print(classification_report(y_test, dt_pred, target_names=['Genuine (0)', 'Fraud (1)']))

# 2. Print metrics for Random Forest
print("================ RANDOM FOREST METRICS ================")
print(classification_report(y_test, rf_pred, target_names=['Genuine (0)', 'Fraud (1)']))

"""# 🏁 Project Executive Summary

### 1. What We Did (The Workflow)
* **Exploratory Data Analysis (EDA)**: Analyzed a massive financial dataset containing 284,807 credit card transactions to check distributions and class ratios.
* **Feature Preprocessing**: Isolated the problem features, removed irrelevant operational columns like `Time`, and handled the `Amount` variable.
* **Pipeline Integrity (Anti-Data Leakage)**: Split the data into training (70%) and testing (30%) sets *before* scaling. Applied `StandardScaler` by fitting strictly on training features and transforming the test features to protect model generalization.
* **Model Selection**: Implemented, tuned, and compared two robust classifiers: a single **Decision Tree** and an ensemble **Random Forest**, both equipped with cost-sensitive `class_weight='balanced'` controls.

### 2. The Core Challenge (The "Accuracy Trap")
* **Extreme Imbalance**: The dataset suffered from a critical class imbalance where **99.827%** of transactions were Genuine (`Class 0`) and only **0.1727%** were Fraudulent (`Class 1`).
* **The Trap**: Standard metrics like `accuracy_score` are completely broken here. A dummy model guessing "Genuine" every time yields 99.83% accuracy while completely missing 100% of financial fraud. The challenge was building a pipeline that aggressively filters fraud while keeping false alarms to a minimum.

### 3. Model Evaluation & Interpretation

| Metric (Fraud Class) | Decision Tree Classifier | Random Forest Classifier (Winner) |
| :--- | :---: | :---: |
| **Overall Accuracy** | 98.00% | 100.00% (99.94%) |
| **Fraud Precision** | 0.09 (9%) | **0.85 (85%)** |
| **Fraud Recall** | **0.84 (84%)** | 0.81 (81%) |
| **Fraud F1-Score** | 0.17 (17%) | **0.83 (83%)** |

#### Key Interpretations:
* **The Decision Tree** acts as an over-aggressive security guard. It catches a high amount of fraud (**84% Recall**), but rings massive false alarms (**9% Precision**). This means out of everyone it blocks, 91% are innocent customers—creating severe business friction and high customer service overhead.
* **The Random Forest** successfully masters the balance. It maintains an outstanding **83% F1-Score**. While its recall drops slightly to 81%, its precision skyrockets to **85%**. It catches the vast majority of actual theft while generating almost zero false alarms for real users.

### 🎯 Final Production Verdict
The **Random Forest Classifier** is chosen as the optimal model for deployment. In a real-world banking framework, it maximizes financial fraud protection while preserving an seamless customer transaction experience.

"""
